### PR TITLE
Add NSUL (National Statistics UPRN Lookup)

### PR DESCRIPTION
**Pull request by tomtaylor**
This will be used by postcode district geometries.

### CODE REVIEW

**Comment by nvkelso** [comment]
PR looks good, with 2 asks:

1. For aggregated (grouped) data sources like this we have a special facility that elevates the individual data sources into a sub list in the main license credit instead of being hurried in the remarks file, to comply with the CC-BY equivalent requirements for each "via" source.

Please see Quattroshapes source for pattern to follow.

2. Also indicate the year of each source, per the sources guidance and our convention for sources that have a regular release cadence.

So in the end the source via section of the main readme would look something more like (will be auto generated):

This source includes CC-BY compatible data from the following organizations:

* **United Kingdom:** Contains OS data © Crown copyright and database right 2023
* **United Kingdom:** Contains Royal Mail data © Royal Mail copyright and Database right 2023
* **United Kingdom:** Contains GeoPlace data © Local Government Information House Limited copyright and database right 2023

**Comment by nvkelso** [comment]
(You can then remove the remarks file and section.)

**Comment by stepps00** [comment]
Other than the same two asks above, this PR looks great. Thanks @tomtaylor 

Here is the Quattroshapes source file that has similar formatting: https://github.com/whosonfirst/whosonfirst-sources/blob/main/sources/quattroshapes.json

**Review by nvkelso — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
